export const theme = {
  colors: {
    primary: '#E53935',
    primaryLight: '#FF6F60',
    primaryDark: '#C62828',
    primaryMuted: '#FFEBEE',
    background: '#F5F5F7',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    text: '#191F28',
    textSecondary: '#8B95A1',
    textTertiary: '#B0B8C1',
    border: '#EEF1F4',
    borderLight: '#F2F4F6',
    success: '#00C48C',
    successMuted: '#E5F8F2',
    warning: '#FF9800',
    warningMuted: '#FFF5E6',
    error: '#E53935',
    errorMuted: '#FFEBEE',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  radius: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    full: 9999,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 3,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  typography: {
    largeTitle: { fontSize: 28, fontWeight: '700' as const, letterSpacing: -0.5 },
    title: { fontSize: 22, fontWeight: '700' as const },
    headline: { fontSize: 18, fontWeight: '600' as const },
    body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodyBold: { fontSize: 16, fontWeight: '600' as const },
    callout: { fontSize: 15, fontWeight: '400' as const },
    caption: { fontSize: 13, fontWeight: '400' as const },
    captionBold: { fontSize: 13, fontWeight: '600' as const },
    label: { fontSize: 14, fontWeight: '600' as const },
  },
};
